services:
  fastgc:
    build: .
    ports:
      - "8083:3000"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastgc.rule=Host(`fastgc.chazmar.com`)"
      - "traefik.http.routers.fastgc.entrypoints=websecure"
      - "traefik.http.routers.fastgc.tls.certresolver=letsencrypt"